[package]
name = "daisy_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package.metadata.docs.rs]
targets = ["thumbv7em-none-eabihf"]

[dependencies]
[workspace]
members = ["hello-daisy"]